name: Build Documentation

on:
  workflow_dispatch:

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.create false

    - name: Install Dependencies
      run: poetry install

    - name: Install Dependencies and Build Documentation
      run: |
        cd docs
        pip3 install -r requirements.docs.txt
        mkdocs gh-deploy --force